/**
 * Queue engine — the heart of FilaZero.
 *
 * Invariants enforced here (and backed by database constraints):
 *   - A queue only accepts new tickets while OPEN.
 *   - A customer holds at most one active ticket per queue
 *     (partial unique index `tickets_one_active_per_user_queue`).
 *   - `ticket_number` is generated by incrementing `queues.ticket_sequence`
 *     while the queue row is locked, so two simultaneous joins never collide.
 *   - "Call next" locks the next WAITING ticket with `FOR UPDATE SKIP LOCKED`,
 *     so two staff members can never receive the same customer.
 *   - State transitions are conditional (`WHERE status = ...`): an invalid
 *     transition is rejected instead of silently applied.
 *
 * `tickets.position` is a cache. The authoritative position is always the
 * ordered set of WAITING tickets, which is what `computeLivePosition` reads.
 */
import "server-only";
import type { Prisma, Ticket, TicketStatus } from "@prisma/client";
import { db, type DbClient } from "@/lib/db";
import { AppError } from "@/lib/errors";
import type { RequestMeta } from "@/lib/http";
import { paginationToSkipTake, type Pagination } from "@/lib/validation";
import { recordAudit } from "@/server/audit/audit.service";
import { createNotification } from "@/server/notifications/notification.service";
import {
  assertBranchAccess,
  assertOrganizationAccess,
  requirePermission,
  type AuthContext,
} from "@/server/context";
import type { Permission } from "@/server/rbac";
import { loadQueueScope } from "@/server/queues/queue.service";
import { publishQueueEvent } from "@/server/realtime/bus";
import { ACTIVE_TICKET_STATUSES, assertTicketTransition } from "./ticket.state";

export { ACTIVE_TICKET_STATUSES, TERMINAL_TICKET_STATUSES } from "./ticket.state";

interface LockedQueueRow {
  id: string;
  status: string;
  organization_id: string;
  branch_id: string;
  ticket_sequence: number;
}

/* -------------------------------------------------------------------------- */
/* Helpers                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Authoritative position of a WAITING ticket: number of WAITING tickets ahead
 * of it (FIFO by joined_at, then ticket_number).
 */
export async function computeLivePosition(
  client: DbClient,
  ticket: { queueId: string; joinedAt: Date; ticketNumber: number },
): Promise<number> {
  const ahead = await client.ticket.count({
    where: {
      queueId: ticket.queueId,
      status: "WAITING",
      OR: [
        { joinedAt: { lt: ticket.joinedAt } },
        {
          joinedAt: ticket.joinedAt,
          ticketNumber: { lt: ticket.ticketNumber },
        },
      ],
    },
  });
  return ahead + 1;
}

/**
 * Rewrites the cached `position` of every WAITING ticket with a single window
 * function, then notifies only the customers whose position actually improved.
 */
async function recomputePositions(
  tx: Prisma.TransactionClient,
  queueId: string,
): Promise<void> {
  const before = await tx.ticket.findMany({
    where: { queueId, status: "WAITING" },
    select: { id: true, position: true },
  });
  const previousByTicket = new Map(before.map((t) => [t.id, t.position]));

  await tx.$executeRaw`
    WITH ranked AS (
      SELECT id, ROW_NUMBER() OVER (ORDER BY joined_at ASC, ticket_number ASC) AS rn
      FROM tickets
      WHERE queue_id = ${queueId}::uuid AND status = 'WAITING'
    )
    UPDATE tickets AS t
    SET position = ranked.rn::int, updated_at = now()
    FROM ranked
    WHERE t.id = ranked.id
  `;

  const after = await tx.ticket.findMany({
    where: { queueId, status: "WAITING" },
    select: { id: true, userId: true, position: true },
  });

  const promoted = after.filter((ticket) => {
    const previous = previousByTicket.get(ticket.id);
    return (
      previous != null &&
      ticket.position != null &&
      ticket.position < previous
    );
  });

  for (const ticket of promoted) {
    await createNotification(tx, {
      userId: ticket.userId,
      type: "POSITION_CHANGED",
      title: "A sua posição mudou",
      message: `A sua nova posição na fila é ${ticket.position}.`,
      ticketId: ticket.id,
    });
  }
}

/** Clears the queue's "current ticket" pointer if it points at this ticket. */
async function clearCurrentTicket(
  tx: Prisma.TransactionClient,
  ticketId: string,
): Promise<void> {
  await tx.queue.updateMany({
    where: { currentTicketId: ticketId },
    data: { currentTicketId: null },
  });
}

/** Loads a ticket for a staff operation and validates tenant access. */
async function requireTicketForStaff(
  client: DbClient,
  ctx: AuthContext,
  ticketId: string,
  permission: Permission,
) {
  const ticket = await client.ticket.findUnique({
    where: { id: ticketId },
    select: {
      id: true,
      userId: true,
      queueId: true,
      ticketNumber: true,
      status: true,
      queue: { select: { organizationId: true, branchId: true, name: true } },
    },
  });
  if (!ticket) throw AppError.notFound("Ticket not found");

  requirePermission(ctx, permission);
  assertOrganizationAccess(ctx, ticket.queue.organizationId);
  assertBranchAccess(ctx, ticket.queue.organizationId, ticket.queue.branchId);
  return ticket;
}

function ticketContext(ticket: Ticket) {
  return {
    id: ticket.id,
    queueId: ticket.queueId,
    userId: ticket.userId,
    ticketNumber: ticket.ticketNumber,
    status: ticket.status,
    position: ticket.position,
    joinedAt: ticket.joinedAt,
    calledAt: ticket.calledAt,
    servingAt: ticket.servingAt,
    completedAt: ticket.completedAt,
    cancelledAt: ticket.cancelledAt,
  };
}

/* -------------------------------------------------------------------------- */
/* Customer operations                                                         */
/* -------------------------------------------------------------------------- */

export async function joinQueue(
  ctx: AuthContext,
  queueId: string,
  meta: RequestMeta,
) {
  requirePermission(ctx, "ticket:join");

  const result = await db.$transaction(async (tx) => {
    // Lock the queue row: serialises ticket_number generation for this queue.
    const rows = await tx.$queryRaw<LockedQueueRow[]>`
      SELECT id, status, organization_id, branch_id, ticket_sequence
      FROM queues
      WHERE id = ${queueId}::uuid
      FOR UPDATE
    `;
    const queue = rows[0];
    if (!queue) throw AppError.notFound("Queue not found");
    if (queue.status !== "OPEN") throw AppError.queueClosed();

    const available = await tx.branch.findFirst({
      where: {
        id: queue.branch_id,
        status: "ACTIVE",
        organization: { status: "ACTIVE" },
      },
      select: { id: true },
    });
    if (!available) throw AppError.queueClosed("This queue is not available");

    const existing = await tx.ticket.findFirst({
      where: {
        queueId,
        userId: ctx.user.id,
        status: { in: ACTIVE_TICKET_STATUSES },
      },
      select: { id: true },
    });
    if (existing) {
      throw AppError.conflict("You already have an active ticket in this queue");
    }

    const ticketNumber = queue.ticket_sequence + 1;
    await tx.queue.update({
      where: { id: queueId },
      data: { ticketSequence: ticketNumber },
    });

    const waitingCount = await tx.ticket.count({
      where: { queueId, status: "WAITING" },
    });
    const position = waitingCount + 1;

    const created = await tx.ticket.create({
      data: {
        queueId,
        userId: ctx.user.id,
        ticketNumber,
        status: "WAITING",
        position,
      },
    });

    await createNotification(tx, {
      userId: ctx.user.id,
      type: "QUEUE_JOINED",
      title: "Entrou na fila",
      message: `O seu ticket é o nº ${ticketNumber} e a sua posição é ${position}.`,
      ticketId: created.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.join",
      entityType: "ticket",
      entityId: created.id,
      metadata: { queueId, ticketNumber, position },
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: created, organizationId: queue.organization_id };
  });

  publishQueueEvent({
    type: "ticket.joined",
    queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

/** The customer's current active ticket, with a freshly computed position. */
export async function getMyActiveTicket(ctx: AuthContext) {
  const ticket = await db.ticket.findFirst({
    where: { userId: ctx.user.id, status: { in: ACTIVE_TICKET_STATUSES } },
    orderBy: { joinedAt: "asc" },
    include: {
      queue: {
        include: {
          branch: { include: { organization: true } },
        },
      },
    },
  });

  if (!ticket) return null;

  const position =
    ticket.status === "WAITING" ? await computeLivePosition(db, ticket) : null;
  const waitingCount = await db.ticket.count({
    where: { queueId: ticket.queueId, status: "WAITING" },
  });

  return {
    ticket: { ...ticketContext(ticket), position },
    waitingCount,
    queue: {
      id: ticket.queue.id,
      name: ticket.queue.name,
      status: ticket.queue.status,
    },
    branch: {
      id: ticket.queue.branch.id,
      name: ticket.queue.branch.name,
      city: ticket.queue.branch.city,
    },
    organization: {
      id: ticket.queue.branch.organization.id,
      name: ticket.queue.branch.organization.name,
      category: ticket.queue.branch.organization.category,
    },
  };
}

export async function listMyTickets(
  ctx: AuthContext,
  pagination: Pagination & { status?: TicketStatus },
) {
  const { skip, take } = paginationToSkipTake(pagination);
  const where = {
    userId: ctx.user.id,
    ...(pagination.status ? { status: pagination.status } : {}),
  };

  const [items, total] = await db.$transaction([
    db.ticket.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip,
      take,
      include: {
        queue: {
          select: {
            id: true,
            name: true,
            branch: { select: { id: true, name: true, city: true } },
            organization: { select: { id: true, name: true } },
          },
        },
      },
    }),
    db.ticket.count({ where }),
  ]);

  return {
    items: items.map((ticket) => ({
      ...ticketContext(ticket),
      queue: ticket.queue,
    })),
    total,
    page: pagination.page,
    pageSize: pagination.pageSize,
  };
}

/** A single ticket: owner, or staff of the owning organization. */
export async function getTicket(ctx: AuthContext, ticketId: string) {
  const ticket = await db.ticket.findUnique({
    where: { id: ticketId },
    include: {
      queue: { include: { branch: { include: { organization: true } } } },
    },
  });
  if (!ticket) throw AppError.notFound("Ticket not found");

  const isOwner = ticket.userId === ctx.user.id;
  if (isOwner) {
    requirePermission(ctx, "ticket:read:self");
  } else {
    requirePermission(ctx, "ticket:read:organization");
    assertOrganizationAccess(ctx, ticket.queue.organizationId);
    assertBranchAccess(ctx, ticket.queue.organizationId, ticket.queue.branchId);
  }

  const position =
    ticket.status === "WAITING" ? await computeLivePosition(db, ticket) : null;

  return {
    ticket: { ...ticketContext(ticket), position },
    queue: {
      id: ticket.queue.id,
      name: ticket.queue.name,
      status: ticket.queue.status,
    },
    branch: {
      id: ticket.queue.branch.id,
      name: ticket.queue.branch.name,
      city: ticket.queue.branch.city,
    },
    organization: {
      id: ticket.queue.branch.organization.id,
      name: ticket.queue.branch.organization.name,
    },
  };
}

/** The customer leaves the queue voluntarily (WAITING only). */
export async function leaveQueue(
  ctx: AuthContext,
  ticketId: string,
  meta: RequestMeta,
) {
  const result = await db.$transaction(async (tx) => {
    const ticket = await tx.ticket.findUnique({
      where: { id: ticketId },
      select: {
        id: true,
        userId: true,
        queueId: true,
        status: true,
        queue: { select: { organizationId: true, branchId: true } },
      },
    });
    if (!ticket) throw AppError.notFound("Ticket not found");
    if (ticket.userId === ctx.user.id) {
      requirePermission(ctx, "ticket:leave:self");
    } else {
      // Someone else's ticket: only staff of the owning organization may act.
      await requireTicketForStaff(tx, ctx, ticketId, "ticket:cancel");
    }
    assertTicketTransition(
      ticket.status,
      "CANCELLED",
      "Only a waiting ticket can be left",
    );

    const updated = await tx.ticket.update({
      where: { id: ticketId },
      data: { status: "CANCELLED", cancelledAt: new Date(), position: null },
    });

    await clearCurrentTicket(tx, ticketId);
    await recomputePositions(tx, ticket.queueId);

    await createNotification(tx, {
      userId: ticket.userId,
      type: "TICKET_CANCELLED",
      title: "Saiu da fila",
      message: "O seu ticket foi cancelado.",
      ticketId: ticket.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.leave",
      entityType: "ticket",
      entityId: ticket.id,
      metadata: { queueId: ticket.queueId },
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: updated, organizationId: ticket.queue.organizationId };
  });

  publishQueueEvent({
    type: "ticket.left",
    queueId: result.ticket.queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

/* -------------------------------------------------------------------------- */
/* Staff operations                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Calls the next waiting customer.
 *
 * The queue row is locked first (so two staff calls for the same queue are
 * serialised), then the next WAITING ticket is taken with SKIP LOCKED.
 */
export async function callNext(
  ctx: AuthContext,
  queueId: string,
  meta: RequestMeta,
) {
  const scope = await loadQueueScope(queueId);
  requirePermission(ctx, "ticket:call");
  assertOrganizationAccess(ctx, scope.organizationId);
  assertBranchAccess(ctx, scope.organizationId, scope.branchId);

  const result = await db.$transaction(async (tx) => {
    const locked = await tx.$queryRaw<{ id: string }[]>`
      SELECT id FROM queues WHERE id = ${queueId}::uuid FOR UPDATE
    `;
    if (locked.length === 0) throw AppError.notFound("Queue not found");

    const inProgress = await tx.ticket.findFirst({
      where: { queueId, status: { in: ["CALLED", "SERVING"] } },
      select: { id: true, ticketNumber: true },
    });
    if (inProgress) {
      throw AppError.invalidState(
        `Ticket nº ${inProgress.ticketNumber} is still in progress`,
      );
    }

    const next = await tx.$queryRaw<{ id: string }[]>`
      SELECT id FROM tickets
      WHERE queue_id = ${queueId}::uuid AND status = 'WAITING'
      ORDER BY joined_at ASC, ticket_number ASC
      FOR UPDATE SKIP LOCKED
      LIMIT 1
    `;
    const nextId = next[0]?.id;
    if (!nextId) throw AppError.invalidState("There are no customers waiting");

    const called = await tx.ticket.update({
      where: { id: nextId },
      data: { status: "CALLED", calledAt: new Date(), position: null },
    });

    await tx.queue.update({
      where: { id: queueId },
      data: { currentTicketId: called.id },
    });
    await recomputePositions(tx, queueId);

    await createNotification(tx, {
      userId: called.userId,
      type: "CUSTOMER_CALLED",
      title: "É a sua vez",
      message: `Dirija-se ao atendimento. Ticket nº ${called.ticketNumber}.`,
      ticketId: called.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.call",
      entityType: "ticket",
      entityId: called.id,
      metadata: { queueId, ticketNumber: called.ticketNumber },
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: called, organizationId: scope.organizationId };
  });

  publishQueueEvent({
    type: "ticket.called",
    queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

export async function startServing(
  ctx: AuthContext,
  ticketId: string,
  meta: RequestMeta,
) {
  const result = await db.$transaction(async (tx) => {
    const ticket = await requireTicketForStaff(tx, ctx, ticketId, "ticket:serve");
    assertTicketTransition(
      ticket.status,
      "SERVING",
      "Only a called ticket can start being served",
    );

    const serving = await tx.ticket.update({
      where: { id: ticketId },
      data: { status: "SERVING", servingAt: new Date() },
    });

    await tx.queue.update({
      where: { id: ticket.queueId },
      data: { currentTicketId: serving.id },
    });

    await createNotification(tx, {
      userId: ticket.userId,
      type: "SERVING_STARTED",
      title: "Atendimento iniciado",
      message: `O atendimento do ticket nº ${ticket.ticketNumber} começou.`,
      ticketId: ticket.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.serve",
      entityType: "ticket",
      entityId: ticket.id,
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: serving, organizationId: ticket.queue.organizationId };
  });

  publishQueueEvent({
    type: "ticket.serving",
    queueId: result.ticket.queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

export async function completeService(
  ctx: AuthContext,
  ticketId: string,
  meta: RequestMeta,
) {
  const result = await db.$transaction(async (tx) => {
    const ticket = await requireTicketForStaff(tx, ctx, ticketId, "ticket:complete");
    assertTicketTransition(
      ticket.status,
      "COMPLETED",
      "Only a serving ticket can be completed",
    );

    const completed = await tx.ticket.update({
      where: { id: ticketId },
      data: { status: "COMPLETED", completedAt: new Date() },
    });

    await clearCurrentTicket(tx, ticketId);
    await recomputePositions(tx, ticket.queueId);

    await createNotification(tx, {
      userId: ticket.userId,
      type: "SERVICE_COMPLETED",
      title: "Atendimento concluído",
      message: `O atendimento do ticket nº ${ticket.ticketNumber} foi concluído.`,
      ticketId: ticket.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.complete",
      entityType: "ticket",
      entityId: ticket.id,
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: completed, organizationId: ticket.queue.organizationId };
  });

  publishQueueEvent({
    type: "ticket.completed",
    queueId: result.ticket.queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

export async function markNoShow(
  ctx: AuthContext,
  ticketId: string,
  meta: RequestMeta,
) {
  const result = await db.$transaction(async (tx) => {
    const ticket = await requireTicketForStaff(tx, ctx, ticketId, "ticket:cancel");
    assertTicketTransition(
      ticket.status,
      "NO_SHOW",
      "Only a called ticket can be marked as no-show",
    );

    const noShow = await tx.ticket.update({
      where: { id: ticketId },
      data: { status: "NO_SHOW", cancelledAt: new Date(), position: null },
    });

    await clearCurrentTicket(tx, ticketId);
    await recomputePositions(tx, ticket.queueId);

    await createNotification(tx, {
      userId: ticket.userId,
      type: "TICKET_CANCELLED",
      title: "Ticket marcado como não compareceu",
      message: `O ticket nº ${ticket.ticketNumber} foi marcado como não compareceu.`,
      ticketId: ticket.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.no_show",
      entityType: "ticket",
      entityId: ticket.id,
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: noShow, organizationId: ticket.queue.organizationId };
  });

  publishQueueEvent({
    type: "ticket.no_show",
    queueId: result.ticket.queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

/**
 * Cancels a ticket. The owner may cancel their own WAITING ticket; staff may
 * cancel WAITING/CALLED/SERVING tickets of their organization.
 */
export async function cancelTicket(
  ctx: AuthContext,
  ticketId: string,
  input: { reason?: string },
  meta: RequestMeta,
) {
  const result = await db.$transaction(async (tx) => {
    const ticket = await tx.ticket.findUnique({
      where: { id: ticketId },
      select: {
        id: true,
        userId: true,
        queueId: true,
        ticketNumber: true,
        status: true,
        queue: { select: { organizationId: true, branchId: true } },
      },
    });
    if (!ticket) throw AppError.notFound("Ticket not found");

    const isOwner = ticket.userId === ctx.user.id;
    if (isOwner) {
      requirePermission(ctx, "ticket:leave:self");
      if (ticket.status !== "WAITING") {
        throw AppError.forbidden(
          "You cannot cancel a ticket that is already being handled",
        );
      }
    } else {
      requirePermission(ctx, "ticket:cancel");
      assertOrganizationAccess(ctx, ticket.queue.organizationId);
      assertBranchAccess(ctx, ticket.queue.organizationId, ticket.queue.branchId);
    }

    assertTicketTransition(
      ticket.status,
      "CANCELLED",
      "This ticket is already finished",
    );

    const cancelled = await tx.ticket.update({
      where: { id: ticketId },
      data: { status: "CANCELLED", cancelledAt: new Date(), position: null },
    });

    await clearCurrentTicket(tx, ticketId);
    await recomputePositions(tx, ticket.queueId);

    await createNotification(tx, {
      userId: ticket.userId,
      type: "TICKET_CANCELLED",
      title: "Ticket cancelado",
      message: input.reason
        ? `O ticket nº ${ticket.ticketNumber} foi cancelado: ${input.reason}`
        : `O ticket nº ${ticket.ticketNumber} foi cancelado.`,
      ticketId: ticket.id,
    });

    await recordAudit(tx, {
      actorUserId: ctx.user.id,
      action: "ticket.cancel",
      entityType: "ticket",
      entityId: ticket.id,
      metadata: { reason: input.reason ?? null },
      ipAddress: meta.ipAddress,
      userAgent: meta.userAgent,
    });

    return { ticket: cancelled, organizationId: ticket.queue.organizationId };
  });

  publishQueueEvent({
    type: "ticket.cancelled",
    queueId: result.ticket.queueId,
    organizationId: result.organizationId,
    ticketId: result.ticket.id,
    ticketNumber: result.ticket.ticketNumber,
    ticketStatus: result.ticket.status,
  });

  return ticketContext(result.ticket);
}

/* -------------------------------------------------------------------------- */
/* Staff queue state                                                           */
/* -------------------------------------------------------------------------- */

export async function getQueueState(
  ctx: AuthContext,
  queueId: string,
  recentLimit: number,
) {
  const scope = await loadQueueScope(queueId);
  requirePermission(ctx, "ticket:read:organization");
  assertOrganizationAccess(ctx, scope.organizationId);
  assertBranchAccess(ctx, scope.organizationId, scope.branchId);

  const [
    queue,
    waiting,
    current,
    recent,
    waitingCount,
    calledCount,
    servingCount,
    completedCount,
    cancelledCount,
    noShowCount,
  ] = await db.$transaction([
    db.queue.findUnique({
      where: { id: queueId },
      include: {
        branch: { select: { id: true, name: true, city: true } },
        organization: { select: { id: true, name: true } },
      },
    }),
    db.ticket.findMany({
      where: { queueId, status: "WAITING" },
      orderBy: [{ joinedAt: "asc" }, { ticketNumber: "asc" }],
      include: { user: { select: { id: true, name: true, phone: true } } },
    }),
    db.ticket.findFirst({
      where: { queueId, status: { in: ["CALLED", "SERVING"] } },
      include: { user: { select: { id: true, name: true, phone: true } } },
    }),
    db.ticket.findMany({
      where: {
        queueId,
        status: { in: ["COMPLETED", "CANCELLED", "NO_SHOW"] },
      },
      orderBy: { updatedAt: "desc" },
      take: recentLimit,
      include: { user: { select: { id: true, name: true } } },
    }),
    db.ticket.count({ where: { queueId, status: "WAITING" } }),
    db.ticket.count({ where: { queueId, status: "CALLED" } }),
    db.ticket.count({ where: { queueId, status: "SERVING" } }),
    db.ticket.count({ where: { queueId, status: "COMPLETED" } }),
    db.ticket.count({ where: { queueId, status: "CANCELLED" } }),
    db.ticket.count({ where: { queueId, status: "NO_SHOW" } }),
  ]);

  if (!queue) throw AppError.notFound("Queue not found");

  return {
    queue: {
      id: queue.id,
      name: queue.name,
      status: queue.status,
      description: queue.description,
    },
    branch: queue.branch,
    organization: queue.organization,
    current,
    waiting,
    recent,
    counts: {
      waiting: waitingCount,
      called: calledCount,
      serving: servingCount,
      completed: completedCount,
      cancelled: cancelledCount,
      noShow: noShowCount,
    },
  };
}
